all:
  hosts:
    redisbasevm1:
      ansible_connection: ssh
      ansible_user: vagrant # Remote user
      ansible_host: {{ redisbasevm1ip_address }} # Remote host
      ansible_port: 22
    redisbasevm2:
      ansible_connection: ssh
      ansible_user: vagrant 
      ansible_host: {{ redisbasevm2ip_address }}
      ansible_port: 22
    redisbasevm3:
      ansible_connection: ssh
      ansible_user: vagrant 
      ansible_host: {{ redisbasevm3ip_address }}
      ansible_port: 22